config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  # 告訴他，我有自己客製化的，不要用內建預設的
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :stories
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # /@[username]/[title]
  get "@:username/:story_id", to: "pages#show", as: "story_page"

  # /@[username]/   當網址只有作者名稱的時候，跑出該作者所有文章
  get "@:username", to: "pages#user", as: "user_page"

  get "/demo", to:"pages#demo"

  # Defines the root path route ("/")
  root "pages#index"

end

app/views/shared/frontend/_flash.html.erb
<div class="notification is-info">
  <%= notice %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
    <!-- 按下之後會回首頁 -->
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>

      <%= link_to "故事列表" , stories_path, class:"navbar-item" %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
          <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            <%= avatar(current_user , size: 50 )%>
            <%= current_user.email %>
          </a>
  
          <div class="navbar-dropdown">
            <%= link_to "新增故事" , new_story_path, class:"navbar-item" %>
            <%= link_to "故事列表" , stories_path, class:"navbar-item" %>
          <hr class="navbar-divider">
          <%= link_to "個人資料" , edit_user_registration_path, data:"get", class:"navbar-item" %>
          <hr class="navbar-divider">
          <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete, "turbo_confirm": "確定是否登出" }, class: "navbar-item"%>
          </div>
        </div>
          <% else %>
          <%= link_to "Log in", new_user_session_path, method: "get", class:"button is-light" %>
          <%= link_to "Sign up", new_user_registration_path , method: "get", class: "button is-primary" %>
          <% end %>
          
        </div>
      </div>
    </div>
  </div>
</nav>