config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  # 告訴他，我有自己客製化的，不要用內建預設的
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :stories
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # /@[username]/[title]
  get "@:username/:story_id", to: "pages#show", as: "story_page"

  # /@[username]/   當網址只有作者名稱的時候，跑出該作者所有文章
  get "@:username", to: "pages#user", as: "user_page"

  get "/demo", to:"pages#demo"

  # Defines the root path route ("/")
  root "pages#index"

end

app/views/pages/demo.html.erb
<div data-controller="demo">
    <input type="text" data-demo-target="output">
    <button data-action="click->demo#pushme">Push</button>
</div>

app/views/pages/index.html.erb
  <section class="columns">
    <!-- left -->
    <section class="column">
      <article>
        <figure class="image">
          <img src="https://fakeimg.pl/350x150/f0f0f0" alt="">
        </figure>
        <h2 class="title is-5">Creating a Pipeline to True Workplace Diversity</h2>
        <p class="content">Providing resources, offering acceptance, and involving people of color are keys to making your company more diverse...</p>
        <footer>
          <p>Arielle Wiltz in Modus</p>
          <p>Aug 7</p>
        </footer>
      </article>
    </section>
    <!-- left -->
    <!-- middle -->
    <section class="column">
      <article class="media">
        <figure class="media-left">
          <img src="https://fakeimg.pl/100x100/">
        </figure>
        <div class="media-content">
          <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
          <footer>
            <p>Arielle Wiltz in Modus</p>
            <p>Aug 7</p>
          </footer>
        </div>
      </article>
      <article class="media">
        <figure class="media-left">
          <img src="https://fakeimg.pl/100x100/">
        </figure>
        <div class="media-content">
          <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
          <footer>
            <p>Arielle Wiltz in Modus</p>
            <p>Aug 7</p>
          </footer>
        </div>
      </article>
      <article class="media">
        <figure class="media-left">
          <img src="https://fakeimg.pl/100x100/">
        </figure>
        <div class="media-content">
          <h2 class="title is-5">I Worked for an Amish Reality TV Show</h2>
          <footer>
            <p>Arielle Wiltz in Modus</p>
            <p>Aug 7</p>
          </footer>
        </div>
      </article>
    </section>
    <!-- middle -->
    <!-- right -->
    <section class="column">
      <article>
        <figure class="image">
          <img src="https://fakeimg.pl/350x200/f0f0f0" alt="">
        </figure>
        <h2 class="title is-5">Creating a Pipeline to True Workplace Diversity</h2>
        <p class="content">Providing resources, offering acceptance, and involving people of color are keys to making your company more diverse...</p>
        <footer>
          <p>Arielle Wiltz in Modus</p>
          <p>Aug 7</p>
        </footer>
      </article>
    </section>
    <!-- right -->
  </section>

  <hr>

  <section class="columns">
    <!-- article list -->
    <section class="column is-two-thirds">

    <% @stories.each do |story| %>
      <article class="media">
        <div class="media-content">
          <h2 class="title is-4">
            <%= link_to story.title, story_page_path(story.user.username, story), class:"has-text-grey-dark" %>
          </h2>
          <p class="content"><%= strip_tags(story.content) %></p>
          <footer>
            <p>
              <%= link_to story.user.username, user_page_path(story.user.username), class:"has-text-grey-dark" %>
              | 最後編輯時間： <%= time_ago_in_words(story.created_at) %>
            </p>
          </footer>
        </div>
        <figure class="media-right">
          <img src="https://fakeimg.pl/150x150/">
        </figure>
      </article>
    <% end %>


    </section>
    <!-- article list -->

    <section class="column">
      <h2 class="title is-4">Popular on Medium</h2>
      <hr>

      <article class="media">
        <div class="media-left">01</div>
        <div class="media-content">
          <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
          <footer>
            <p>Thomas Oppong</p>
          </footer>
        </div>
      </article>

      <article class="media">
        <div class="media-left">02</div>
        <div class="media-content">
          <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
          <footer>
            <p>Thomas Oppong</p>
          </footer>
        </div>
      </article>

      <article class="media">
        <div class="media-left">03</div>
        <div class="media-content">
          <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
          <footer>
            <p>Thomas Oppong</p>
          </footer>
        </div>
      </article>

      <article class="media">
        <div class="media-left">04</div>
        <div class="media-content">
          <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
          <footer>
            <p>Thomas Oppong</p>
          </footer>
        </div>
      </article>

      <article class="media">
        <div class="media-left">05</div>
        <div class="media-content">
          <h3>Difficult Conversation Lessons From a Psychologist Who’s Been Dealing With People</h3>
          <footer>
            <p>Thomas Oppong</p>
          </footer>
        </div>
      </article>
    </section>
  </section>