config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  # 告訴他，我有自己客製化的，不要用內建預設的
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :stories
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # /@[username]/[title]
  get "@:username/:story_id", to: "pages#show", as: "story_page"

  # /@[username]/   當網址只有作者名稱的時候，跑出該作者所有文章
  get "@:username", to: "pages#user", as: "user_page"

  get "/demo", to:"pages#demo"

  # Defines the root path route ("/")
  root "pages#index"

end

app/models/story.rb
class Story < ApplicationRecord
  include AASM
  belongs_to :user
  validates :title, presence: true
  default_scope {where(delete_at: nil)}
 # 上面那行加上去後，所有查詢動作時都會預設加上的delte_at的值是nil的篩選
 # 也就是會找出沒有被軟刪除的資料
 
  extend FriendlyId
  friendly_id :slug_candidate, use: :slugged 
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  has_one_attached :cover_image



  # 覆寫destroy方法
  def destroy
    update(delete_at: Time.now)
    # 在这个方法内,它使用update方法来将deleted_at字段更新为当前时间。 
    # 所以记录不会被真正删除,只是打上一个deleted_at标记。
    # 这种方式即实现了逻辑上的“删除”,又保留了数据,达到软删除的目的。
    # 后续通过Scopes或查询时,可以根据deleted_at是否存在来判断记录是否被删除。
  end

  aasm(column: "status", no_direct_assignment: true) do 
    # gem本身預設是有個column，現在告訴他我們要用status當作參考
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :draft
    end
  end


  private
  def slug_candidate  
    [
      :title, 
      [:title, SecureRandom.hex[0,8]]
    # 用title加上安全模組製造的隨機數，然後取八位數
    ]
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

    before_action :authenticate_user!
    before_action :find_story, only:[:edit, :update, :destroy]
        # 在這個controllser，只要進行action前沒有登入，就把沒有登入的使用者踢回登入畫面
        # 也可限定單個action   後面加上only: [:new]  或是濾掉except


        
    def index
        @stories = current_user.stories.order(created_at: :desc)
        # 按照建立時間降階排序
    end
    
    def new     
        # @story = Story.new 可以改寫成下面那行，只要在user.rb加上 has_many :stories
        @story = current_user.stories.new
        
    end

    def create
        @story = current_user.stories.new(story_params)
        # 按下發布文章的按鈕之後，會多個參數publish出現，然後就將status設為publish
        @story.publish! if params[:publish]

        if @story.save
            if params[:publish]
                redirect_to stories_path, notice: "已成功發布"
            else
                redirect_to edit_story_path(@story), notice: "已儲存"
            end
            # 如果有:publish這個參數，就回到故事列表，沒有的話就回到(停在)該故事的edit畫面
        else
            render :new
            #重新渲染new的畫面
            #  puts @story.errors.full_messages # 將錯誤訊息輸出到控制台
        end
    end

    def edit
    end


    def update
        if @story.update(story_params)
            case
            when params[:publish]
                @story.publish!
                redirect_to stories_path, notice: "故事已發佈"
            when params[:unpublish]
                @story.unpublish!
                redirect_to stories_path, notice: "故事已下架"
            else
                redirect_to edit_story_path(@story), notice: "故事已儲存"
            end
        else
            render :edit
        end
    end

    def destroy
        @story.destroy
        redirect_to stories_path, notice: "故事已刪除"
    end


    # 針對送過來的資料進行清洗，只允許給過的東西進資料庫
    private
    def story_params
        params.require(:story).permit(:title, :content, :cover_image)
    end

    def find_story
        @story = current_user.stories.friendly.find(params[:id])
    end



end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<% if story.errors.any? %>
    hi
    <div class="notification is-danger">
        <%= story.errors.full_messages.to_sentence %>
    </div>
<% end %>

<%= form_for(story) do |form| %>
    <div class="field">
        <%= image_tag story.cover_image, class: "cover_image" if story.cover_image.attached? %>
        <div>
            <%= form.label :cover_image, "封面圖" %>
            <%= form.file_field :cover_image %>
        </div>

    </div>    
    <div class="field">
        <%= form.label :title, "文章標題" , class: "input" %>
        <%= form.text_field :title , class: "input is-primary is-medium" %>
    </div>
    <div class="field">
        <%= form.label :content, "文章內容" , class: "input" %>
        <%= form.text_area :content , rows: 10, class: "textarea is-primary is-medium" %>
    </div>
    <div class="field">
        <%= form.submit "儲存草稿",class: "button is-medium", name: "save_as_draft" %>
        <%= form.submit "發布文章",class: "button is-medium is-primary",  name: "publish"  if story.may_publish? %>
        <%= form.submit "文章下架",class: "button is-medium is-danger",  name: "unpublish"  if story.may_unpublish? %>

    </div>
<% end %>

app/views/stories/edit.html.erb
<h1 class="title">編輯故事</h1>

<%= render "form", story: @story %>

app/views/stories/index.html.erb
<h1 class="title">文章列表</h1>


<% @stories.each do |story| %>
    <div class="content">
        <h2 class="title">
            <%= link_to story.title, edit_story_path(story), class:"has-text-grey-darker" %>  
            <%= content_tag :span, "已發佈", class:"tag is-primary is-small" if story.published? %>  
        </h2>

        <p><%= story.content %> </p>
        <p>
            最後編輯時間： <%= time_ago_in_words(story.updated_at) %>
            <%= link_to "編輯", edit_story_path(story) , class:"button is-text is-small" %>
            <%= link_to "刪除", story_path(story) ,data:{"turbo-method": :delete, "turbo-confirm": "確認刪除"} , class:"button is-danger is-small" %>
        </p>
    </div>
    <hr>
<% end %>



app/views/stories/new.html.erb
<h1 class="title">新增故事</h1>

<%= render "form", story: @story %>